### ISSUE TITLE
Is it possible to expand it to SDK3.0/Basalt?

### ISSUE THREAD

**Issue by PanicMan** [gregoiresage/pebble-gbitmap-lib#1]
Hello,

I want to use that lib on Basalt/Pebble Time, with a color Bitmap.
Is it possible to expand it, that it works with color Bitmaps?

Thanks a lot!

Greetings Jack

**Comment by gregoiresage** [comment]
Hey Jack,

I will do asap, it is not complex

2015-05-30 13:07 GMT+02:00 Jack notifications@github.com:

**Comment by PanicMan** [comment]
Thanks a lot!

Could you please leave here an comment if it is done?

2015-05-31 0:14 GMT+02:00 Grégoire Sage notifications@github.com:

**Comment by gregoiresage** [comment]
It should work now :-p

**Comment by PanicMan** [comment]
Great! Thanks a lot!

2015-06-02 23:10 GMT+02:00 Grégoire Sage notifications@github.com:
