### ISSUE TITLE
Doesn't 'resize' or 'scale'

### ISSUE THREAD

**Issue by RealZogzog** [gregoiresage/pebble-gbitmap-lib#2]
I find the description deceptive as your library only shrink bitmaps...

**Comment by gregoiresage** [comment]
Feel free to add new features!

**Comment by RealZogzog** [comment]
I'll most likely make my own lib.
I only need to scale up my bitmap so your "resize" library is useless to me.
And I think you should change the description of your project as it does not reflect the functions provided.

**Comment by gregoiresage** [comment]
Comment the [line 111](https://github.com/gregoiresage/pebble-gbitmap-lib/blob/master/src/gbitmap_tools.c#L111) and enjoy the scale feature

**Comment by RealZogzog** [comment]
already tried that, didn't work...

**Comment by gregoiresage** [comment]
It worked for my tests. You probably tried to make a bitmap too large and you don't have enough memory...
